# Generated by Django 6.0 on 2026-01-16 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_userprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address_line1',
            field=models.CharField(blank=True, default='123 Insurance Plaza', max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, default='New York', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(default='InsureTech Solutions', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_tagline',
            field=models.CharField(blank=True, default='Protecting What Matters Most', max_length=500),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(default='info@insuretech.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, default='+1 (555) 123-4567', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='postal_code',
            field=models.CharField(blank=True, default='10001', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='primary_color',
            field=models.CharField(default='#FF6B4A', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='secondary_color',
            field=models.CharField(default='#2C3E50', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='state',
            field=models.CharField(blank=True, default='NY', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, default='https://insuretech.com'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('CLAIMS_ADJUSTER', 'Claims Adjuster'), ('UNDERWRITER', 'Underwriter'), ('FRAUD_INVESTIGATOR', 'Fraud Investigator'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=50),
        ),
        migrations.AlterModelTable(
            name='companyprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('CLAIMS_ADJUSTER', 'Claims Adjuster'), ('UNDERWRITER', 'Underwriter'), ('FRAUD_INVESTIGATOR', 'Fraud Investigator'), ('VIEWER', 'Viewer')], max_length=50)),
                ('permission', models.CharField(choices=[('can_create_super_admin', 'Can Create Super Admin'), ('can_create_admin', 'Can Create Admin'), ('can_create_users', 'Can Create Users'), ('can_manage_users', 'Can Manage Users'), ('can_delete_users', 'Can Delete Users'), ('can_view_policyholders', 'Can View Policyholders'), ('can_view_vehicles', 'Can View Vehicles'), ('can_view_policies', 'Can View Policies'), ('can_view_claims', 'Can View Claims'), ('can_view_fraud_detection', 'Can View Fraud Detection'), ('can_create_policyholders', 'Can Create Policyholders'), ('can_edit_policyholders', 'Can Edit Policyholders'), ('can_delete_policyholders', 'Can Delete Policyholders'), ('can_create_policies', 'Can Create Policies'), ('can_edit_policies', 'Can Edit Policies'), ('can_delete_policies', 'Can Delete Policies'), ('can_process_claims', 'Can Process Claims'), ('can_approve_claims', 'Can Approve Claims'), ('can_delete_claims', 'Can Delete Claims'), ('can_use_fraud_detection', 'Can Use Fraud Detection'), ('can_flag_fraud', 'Can Flag Fraud'), ('can_calculate_premium', 'Can Calculate Premium'), ('can_estimate_claims', 'Can Estimate Claims'), ('can_export_reports', 'Can Export Reports')], max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'indexes': [models.Index(fields=['role', 'permission'], name='dashboard_r_role_b35aca_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
