# Generated by Django 6.0 on 2026-04-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_companyprofile_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_defensive_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_driving_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_medical_license_valid',
            field=models.BooleanField(default=False),
        ),
    ]
