# Generated by Django 6.0 on 2026-05-20 20:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_premium_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.05'), max_digits=5)),
                ('minimum_premium', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('labor_rate_per_hour', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=10)),
                ('addon_roadside_assistance', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10)),
                ('addon_rental_coverage', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=10)),
                ('addon_glass_coverage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=10)),
                ('surcharge_young_driver', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=5)),
                ('surcharge_senior_driver', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('surcharge_poor_credit', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=5)),
                ('discount_excellent_credit', models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5)),
                ('threshold_auto_approve', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10)),
                ('threshold_manual_review', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('threshold_fraud_reject', models.FloatField(default=0.5)),
                ('threshold_variance_warning', models.FloatField(default=0.2)),
            ],
            options={
                'verbose_name': 'Global Pricing Settings',
            },
        ),
    ]
