# Generated by Django 6.0 on 2026-05-20 22:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalpricingsettings',
            options={'verbose_name': 'Global Pricing Settings', 'verbose_name_plural': 'Global Pricing Settings'},
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='allow_multi_currency',
            field=models.BooleanField(default=True, help_text='Allow users to select ZWG in addition to USD when creating policies'),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'US Dollar (USD)'), ('ZWG', 'Zimbabwe Gold (ZWG)')], default='USD', help_text='Default currency applied to new policies and quotes', max_length=3),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='discount_anti_theft',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), help_text='Discount when vehicle has an anti-theft device (e.g. 0.05 = −5 %)', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='ratio_legal_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Portion attributed to legal fees', max_digits=3),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='ratio_medical_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.20'), help_text='Portion attributed to medical expenses', max_digits=3),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='ratio_other_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Portion attributed to other costs', max_digits=3),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='ratio_vehicle_damage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='Portion of estimated cost attributed to vehicle damage', max_digits=3),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='sev_major_mult',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.350'), help_text="'Major Damage' claim = this × vehicle value", max_digits=4),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='sev_minor_mult',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.150'), help_text="'Minor Damage' claim = this × vehicle value", max_digits=4),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='sev_moderate_mult',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.300'), help_text="'Moderate' damage claim = this × vehicle value", max_digits=4),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='sev_total_mult',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text="'Total Loss' claim = this × vehicle value (typically 1.0)", max_digits=4),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='sev_trivial_mult',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.050'), help_text="'Trivial Damage' claim = this × vehicle value", max_digits=4),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='zwg_usd_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('13.5600'), help_text='ZWG per 1 USD — used for display conversion (e.g. 13.56)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='addon_glass_coverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Flat fee added to premium for glass/windscreen cover', max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='addon_rental_coverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Flat fee added to premium for rental-car cover', max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='addon_roadside_assistance',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Flat fee added to premium for roadside-assistance cover', max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='base_premium_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), help_text='Percentage of vehicle market value used as the base premium (e.g. 0.05 = 5 %)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='discount_excellent_credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Discount when credit score ≥ 750 (e.g. 0.10 = −10 %)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='labour_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='Repair labour rate used in claims cost estimation', max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='minimum_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Absolute minimum premium charged on any policy', max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='surcharge_poor_credit',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.20'), help_text='Surcharge when credit score < 600 (e.g. 0.20 = +20 %)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='surcharge_senior_driver',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Surcharge for drivers over 65 (e.g. 0.10 = +10 %)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='surcharge_young_driver',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), help_text='Surcharge for drivers under 25 (e.g. 0.15 = +15 %)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='threshold_auto_approve',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Claims at or below this amount are auto-approved', max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='threshold_fraud_reject',
            field=models.FloatField(default=0.5, help_text='ML fraud-score at which a claim is auto-rejected (0 – 1)'),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='threshold_manual_review',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Claims above this amount are escalated to manual review', max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalpricingsettings',
            name='threshold_variance_warning',
            field=models.FloatField(default=0.2, help_text='Fraud-score / variance level that triggers a warning review (0 – 1)'),
        ),
    ]
