# Generated by Django 6.0 on 2026-05-21 23:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_alter_globalpricingsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpricingsettings',
            name='age_threshold_senior_driver',
            field=models.IntegerField(default=65, help_text='Age above which senior driver surcharge applies'),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='age_threshold_young_driver',
            field=models.IntegerField(default=25, help_text='Age below which young driver surcharge applies'),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='credit_threshold_excellent',
            field=models.IntegerField(default=750, help_text='Credit score at/above which excellent credit discount applies'),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='credit_threshold_poor',
            field=models.IntegerField(default=600, help_text='Credit score below which poor credit surcharge applies'),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='discount_loyalty',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Loyalty discount percentage (e.g. 0.10 = -10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='loyalty_years_threshold',
            field=models.IntegerField(default=5, help_text='Years with company required for loyalty discount'),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='minimum_coverage_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Minimum allowable coverage amount for any policy', max_digits=10),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='surcharge_modified_vehicle',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), help_text='Surcharge for modified vehicles (e.g. 0.15 = +15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='surcharge_old_vehicle',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Surcharge for vehicles older than threshold (e.g. 0.10 = +10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='globalpricingsettings',
            name='vehicle_age_threshold_old',
            field=models.IntegerField(default=10, help_text='Vehicle age (years) above which old vehicle surcharge applies'),
        ),
    ]
