# Generated by Django 6.0 on 2026-01-13 10:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud_detection', '0002_policyholder_credit_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='ML predicted settlement cost', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('confidence_score', models.FloatField(default=0.0, help_text='Model confidence in prediction (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence_lower_bound', models.DecimalField(decimal_places=2, help_text='Lower bound of confidence interval', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('confidence_upper_bound', models.DecimalField(decimal_places=2, help_text='Upper bound of confidence interval', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('predicted_severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], help_text='ML predicted claim severity', max_length=20)),
                ('severity_score', models.FloatField(default=0.0, help_text='Severity score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recommended_reserve', models.DecimalField(decimal_places=2, help_text='Recommended reserve amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserve_adequacy_ratio', models.FloatField(default=1.0, help_text='Ratio of reserve to estimated cost', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('processing_recommendation', models.CharField(choices=[('AUTO_APPROVE', 'Auto Approve'), ('MANUAL_REVIEW', 'Manual Review Required'), ('DETAILED_INVESTIGATION', 'Detailed Investigation'), ('REJECT', 'Recommend Rejection')], default='MANUAL_REVIEW', max_length=30)),
                ('triage_priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('estimated_processing_days', models.IntegerField(default=7, help_text='Estimated days to process claim', validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_breakdown', models.JSONField(blank=True, default=dict, help_text='Detailed cost breakdown by category')),
                ('risk_factors', models.JSONField(blank=True, default=dict, help_text='Factors contributing to cost estimate')),
                ('actual_settlement_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual settlement amount (for model validation)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('prediction_accuracy', models.FloatField(blank=True, help_text='Accuracy of prediction compared to actual', null=True)),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('features_used', models.JSONField(blank=True, default=list, help_text='List of features used in prediction')),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Manual adjustment by claims adjuster', max_digits=12)),
                ('adjustment_reason', models.TextField(blank=True, null=True)),
                ('adjusted_by', models.CharField(blank=True, max_length=100, null=True)),
                ('final_estimate', models.DecimalField(decimal_places=2, help_text='Final estimate after adjustments', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimate', to='fraud_detection.claim')),
            ],
            options={
                'verbose_name': 'Claim Estimate',
                'verbose_name_plural': 'Claim Estimates',
                'db_table': 'claim_estimates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ESTIMATE_GENERATED', 'Estimate Generated'), ('TRIAGE_ASSIGNED', 'Triage Priority Assigned'), ('RECOMMENDATION_MADE', 'Processing Recommendation Made'), ('RESERVE_CALCULATED', 'Reserve Amount Calculated'), ('MANUAL_REVIEW_TRIGGERED', 'Manual Review Triggered'), ('AUTO_APPROVED', 'Auto Approved'), ('FRAUD_FLAG_RAISED', 'Fraud Flag Raised'), ('ESTIMATE_UPDATED', 'Estimate Updated'), ('COST_RECALCULATED', 'Cost Recalculated')], max_length=30)),
                ('action_description', models.TextField()),
                ('is_automated', models.BooleanField(default=True)),
                ('performed_by', models.CharField(default='SYSTEM', help_text='User or SYSTEM', max_length=100)),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Detailed results of the action')),
                ('previous_value', models.CharField(blank=True, max_length=200, null=True)),
                ('new_value', models.CharField(blank=True, max_length=200, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Time taken to process action (milliseconds)', null=True)),
                ('model_version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='fraud_detection.claim')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='claims_automation.claimestimate')),
            ],
            options={
                'verbose_name': 'Claim Processing Log',
                'verbose_name_plural': 'Claim Processing Logs',
                'db_table': 'claim_processing_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='claimestimate',
            index=models.Index(fields=['estimate_number'], name='claim_estim_estimat_3841d1_idx'),
        ),
        migrations.AddIndex(
            model_name='claimestimate',
            index=models.Index(fields=['claim'], name='claim_estim_claim_i_b96125_idx'),
        ),
        migrations.AddIndex(
            model_name='claimestimate',
            index=models.Index(fields=['predicted_severity'], name='claim_estim_predict_a559c4_idx'),
        ),
        migrations.AddIndex(
            model_name='claimestimate',
            index=models.Index(fields=['triage_priority'], name='claim_estim_triage__e160f3_idx'),
        ),
        migrations.AddIndex(
            model_name='claimestimate',
            index=models.Index(fields=['processing_recommendation'], name='claim_estim_process_3ebe3e_idx'),
        ),
        migrations.AddIndex(
            model_name='claimestimate',
            index=models.Index(fields=['created_at'], name='claim_estim_created_236144_idx'),
        ),
        migrations.AddIndex(
            model_name='claimprocessinglog',
            index=models.Index(fields=['claim'], name='claim_proce_claim_i_896c66_idx'),
        ),
        migrations.AddIndex(
            model_name='claimprocessinglog',
            index=models.Index(fields=['estimate'], name='claim_proce_estimat_abec6b_idx'),
        ),
        migrations.AddIndex(
            model_name='claimprocessinglog',
            index=models.Index(fields=['action_type'], name='claim_proce_action__77bbff_idx'),
        ),
        migrations.AddIndex(
            model_name='claimprocessinglog',
            index=models.Index(fields=['is_automated'], name='claim_proce_is_auto_347b41_idx'),
        ),
        migrations.AddIndex(
            model_name='claimprocessinglog',
            index=models.Index(fields=['created_at'], name='claim_proce_created_afe929_idx'),
        ),
    ]
