# Generated by Django 6.0 on 2026-01-12 10:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud_detection', '0002_policyholder_credit_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('policy_type', models.CharField(choices=[('COMPREHENSIVE', 'Comprehensive'), ('THIRD_PARTY', 'Third Party'), ('COLLISION', 'Collision'), ('LIABILITY', 'Liability')], max_length=20)),
                ('coverage_level', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('SENT', 'Sent to Customer'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CONVERTED', 'Converted to Policy')], default='DRAFT', max_length=20)),
                ('customer_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('customer_credit_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('customer_years_experience', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('vehicle_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('vehicle_make', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vehicle_has_anti_theft', models.BooleanField(default=False)),
                ('vehicle_is_modified', models.BooleanField(default=False)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('base_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('risk_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional premium based on risk factors', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ml_predicted_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Premium predicted by ML model', max_digits=10)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Model confidence in prediction (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_factors', models.JSONField(blank=True, default=dict, help_text='Breakdown of risk factors affecting price')),
                ('has_roadside_assistance', models.BooleanField(default=False)),
                ('has_rental_coverage', models.BooleanField(default=False)),
                ('has_glass_coverage', models.BooleanField(default=False)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('converted_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='fraud_detection.policy')),
                ('policyholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='fraud_detection.policyholder')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='fraud_detection.vehicle')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('new_premium', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('premium_change', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('premium_change_percentage', models.FloatField(default=0.0, help_text='Percentage change in premium')),
                ('change_reason', models.CharField(choices=[('NEW_POLICY', 'New Policy'), ('RENEWAL', 'Policy Renewal'), ('RISK_CHANGE', 'Risk Profile Change'), ('CLAIM_FILED', 'Claim Filed'), ('MARKET_ADJUSTMENT', 'Market Adjustment'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('DISCOUNT_APPLIED', 'Discount Applied'), ('COVERAGE_CHANGE', 'Coverage Change')], max_length=30)),
                ('change_description', models.TextField(blank=True, null=True)),
                ('risk_score_snapshot', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('risk_factors_snapshot', models.JSONField(blank=True, default=dict, help_text='Risk factors at time of pricing')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(default='SYSTEM', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='fraud_detection.policy')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_history', to='dynamic_pricing.quote')),
            ],
            options={
                'verbose_name': 'Price History',
                'verbose_name_plural': 'Price Histories',
                'db_table': 'price_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_number'], name='quotes_quote_n_a300f2_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='quotes_status_b396a9_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['policyholder'], name='quotes_policyh_160ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['vehicle'], name='quotes_vehicle_ceda58_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['created_at'], name='quotes_created_c74d71_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['valid_until'], name='quotes_valid_u_b76eec_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['policy'], name='price_histo_policy__71f179_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['effective_from', 'effective_to'], name='price_histo_effecti_df5ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['change_reason'], name='price_histo_change__06aaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['created_at'], name='price_histo_created_be9adc_idx'),
        ),
    ]
