# Generated by Django 6.0 on 2026-04-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='vehicle_year',
            new_name='vehicle_manufacture_year',
        ),
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ZWG', 'ZWG')], default='USD', max_length=3),
        ),
    ]
