# Generated by Django 6.0 on 2026-01-06 20:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policyholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_holder_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('occupation', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self Employed'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('STUDENT', 'Student')], max_length=50)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_score', models.IntegerField(help_text='Credit score between 300 and 850', validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)])),
                ('years_with_company', models.IntegerField(default=0, help_text='Number of years as customer', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Policyholder',
                'verbose_name_plural': 'Policyholders',
                'db_table': 'policyholders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='policyholde_email_f35d16_idx'), models.Index(fields=['policy_holder_id'], name='policyholde_policy__5966bd_idx'), models.Index(fields=['last_name', 'first_name'], name='policyholde_last_na_a66666_idx'), models.Index(fields=['created_at'], name='policyholde_created_77d3fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('COUPE', 'Coupe'), ('HATCHBACK', 'Hatchback'), ('SPORTS', 'Sports Car')], max_length=20)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN must be 17 characters (excluding I, O, Q)', regex='^[A-HJ-NPR-Z0-9]{17}$')])),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('engine_capacity', models.IntegerField(help_text='Engine capacity in CC', validators=[django.core.validators.MinValueValidator(500)])),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('CNG', 'CNG')], max_length=20)),
                ('seating_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(50)])),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('odometer_reading', models.IntegerField(help_text='Current odometer reading in miles', validators=[django.core.validators.MinValueValidator(0)])),
                ('has_anti_theft', models.BooleanField(default=False)),
                ('has_airbags', models.BooleanField(default=True)),
                ('has_abs', models.BooleanField(default=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fraud_detection.policyholder')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('policy_type', models.CharField(choices=[('COMPREHENSIVE', 'Comprehensive'), ('THIRD_PARTY', 'Third Party'), ('COLLISION', 'Collision'), ('LIABILITY', 'Liability')], max_length=20)),
                ('coverage_level', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deductible', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('has_roadside_assistance', models.BooleanField(default=False)),
                ('has_rental_coverage', models.BooleanField(default=False)),
                ('has_glass_coverage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='fraud_detection.policyholder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='fraud_detection.vehicle')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('claim_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('THEFT', 'Theft'), ('VANDALISM', 'Vandalism'), ('NATURAL_DISASTER', 'Natural Disaster'), ('FIRE', 'Fire'), ('OTHER', 'Other')], max_length=30)),
                ('claim_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('TOTAL_LOSS', 'Total Loss')], max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('incident_location', models.CharField(max_length=255)),
                ('incident_description', models.TextField()),
                ('police_report_filed', models.BooleanField(default=False)),
                ('police_report_number', models.CharField(blank=True, max_length=50, null=True)),
                ('witnesses_present', models.BooleanField(default=False)),
                ('number_of_witnesses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_vehicles_involved', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_injuries', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('third_party_involved', models.BooleanField(default=False)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('approved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fraud_score', models.FloatField(default=0.0, help_text='Fraud probability score from ML model (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_fraudulent', models.BooleanField(default=False)),
                ('fraud_reason', models.TextField(blank=True, null=True)),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='fraud_detection.policy')),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='fraud_detection.policyholder')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='fraud_detection.vehicle')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'claims',
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_id'], name='vehicles_vehicle_06c6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vin'], name='vehicles_vin_42311c_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicles_registr_eb8990_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['policyholder'], name='vehicles_policyh_305133_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_policy__ca1bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['status'], name='policies_status_d09338_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policyholder'], name='policies_policyh_03b2a6_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['vehicle'], name='policies_vehicle_f1eb56_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['start_date', 'end_date'], name='policies_start_d_34ca2f_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_number'], name='claims_claim_n_b9e177_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_status'], name='claims_claim_s_64d69d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policy'], name='claims_policy__d2422d_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['policyholder'], name='claims_policyh_bed856_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['incident_date'], name='claims_inciden_ecb07b_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['is_fraudulent'], name='claims_is_frau_a10e3b_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['fraud_score'], name='claims_fraud_s_d1e303_idx'),
        ),
    ]
