# Generated by Django 6.0 on 2026-01-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='credit_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
