# Generated by Django 6.0 on 2026-04-23 00:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection', '0002_policyholder_credit_rating_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicles_vehicle_06c6b1_idx',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='year',
            new_name='manufacture_year',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='incident_description',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='number_of_injuries',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='number_of_witnesses',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='police_report_filed',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='police_report_number',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='third_party_involved',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='witnesses_present',
        ),
        migrations.RemoveField(
            model_name='policyholder',
            name='annual_income',
        ),
        migrations.RemoveField(
            model_name='policyholder',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='claim',
            name='incident_evidence',
            field=models.FileField(blank=True, help_text='Upload evidence file (photos, documents, etc.)', null=True, upload_to='claim_evidence/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='payment_method',
            field=models.CharField(choices=[('SWIPE', 'Swipe Card'), ('ECOCASH', 'EcoCash'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer')], default='BANK_TRANSFER', help_text='Preferred payment method for claim settlement', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='has_defensive_license',
            field=models.BooleanField(default=False, help_text='Has defensive driving certificate'),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='has_driving_license',
            field=models.BooleanField(default=False, help_text='Has valid driving license'),
        ),
        migrations.AddField(
            model_name='policyholder',
            name='is_medical_license_valid',
            field=models.BooleanField(default=True, help_text='Medical fitness certificate is valid'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated based on policy coverage', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid'), ('CLOSED', 'Closed')], default='SUBMITTED', help_text='Auto-determined from policy status', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated from damage assessment', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='claim',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-set when payment is processed', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated coverage amount', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='deductible',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated deductible amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated premium amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='country',
            field=models.CharField(default='Zimbabwe', max_length=100),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='credit_rating',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent (750-850)'), ('GOOD', 'Good (700-749)'), ('FAIR', 'Fair (650-699)'), ('POOR', 'Poor (600-649)'), ('VERY_POOR', 'Very Poor (300-599)')], help_text='Auto-calculated based on credit score', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='credit_score',
            field=models.IntegerField(blank=True, help_text='Auto-calculated credit score between 300 and 850', null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(850)]),
        ),
        migrations.AlterField(
            model_name='policyholder',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
    ]
